site:
    title: Angular Effects // Docs
    url: https://ngfx.io/
content:
    sources:
        - url: .
          branches: HEAD
          start_path: ./docs
output:
    dir: ./dist/docs
ui:
    bundle:
        url: https://github.com/stupidawesome/antora-default-ui/raw/master/build/ui-bundle.zip
        snapshot: true
    supplemental_files: ./docs/supplemental_ui
