= Changelog

== 9.1.0-next.3

=== Features

- add `ngOnConnect` hook

Similar to `setup` from Vue, but called after the component is constructed. It receives a reactive `this` context so that effects are automatically triggered when values change. When state is updated outside of `ngOnConnect`, such as when a button triggers `incrementCount`, its value is propagated to effects on the next change detection run. Template events automatically trigger change detection so no manual change detection is required. A non reactive reference to the component can be injected with `useContext()`.

Example:

[source, typescript]
----
@Component({
    providers: [Connectable],
})
export class MyComponent implements Connectable {
    count: number = 0

    incrementCount() {
        this.count += 1
    }

    ngOnConnect() {
        const http = inject(HttpClient)
        const context = useContext<this>() // non reactive

        effect(() => {
            console.log(this.count)
        })
    }

    constructor(connect: Connect) {
        connect(this)
    }
}
----

Effects can be composed by calling functions inside the `ngOnConnect` hook, or provided as a `Connectable` in the providers array.

[source, typescript]
----
// Connectable provider
const MyConnectable = connectable<MyComponent>((state) => {
    effect(() => console.log("MyConnectable"))
})

// Composable function
function useConnectable(state: MyComponent) {
    effect(() => console.log("useConnectable"))
}

@Component({
    providers: [Connectable, MyConnectable]
})
export class MyComponent {
    ngOnConnect() {
        // pass in the reactive context
        useConnectable(this)

        effect(() => console.log("ngOnConnect"))
    }

    constructor(connect: Connect) {
        // calls ngOnConnect() and runs MyConnectable
        connect(this)
    }
}
----

== 9.1.0-next.2

=== Features

- add experimental composition API

This library will be introducing a compositional API that works similar to Vue 3.0. This isn't a breaking change, but
the plan is to deprecate the decorator based API in favour of this one.

[source, typescript]
----
export const Connectable = connectable<CompositionComponent>(state => {
    effect(() => { // runs immediately and every time count changes
        return timer(1000).subscribe(() => {
            state.count += 1
        })
    })
})

@Component({
    providers: [Connectable]
})
export class MyComponent {
    count = 0
    constructor(connect: Connect) {
        connect(this)
    }
}

----

== 9.1.0-next.1

Removed

== 9.1.0-next.0

=== Features

- add groundwork for composition API

== 9.0.7

=== Bug fixes

- ensure reactive state is updated when inputs change

== 9.0.6

=== Bug fixes

- fix types for TypeScript 3.8

== 9.0.5

=== Bug fixes

- fix bug caused by importing `BrowserAnimationsModule` (closes #6)

== 9.0.4

=== Bug fixes

- fix assignment to effect bindings with union types

== 9.0.3

=== Bug fixes

- fix typings for changes operator

== 9.0.2

=== Bug fixes

- improve effect adapter typings
- fix options for effect adapters that supply non-object arguments

== 9.0.1

No changes

== 9.0.0

=== Features

- allow effect adapters to invoke effects and customise their arguments

=== BREAKING CHANGES

Effect adapters that implement the `CreateEffectAdapter` interface now receive the whole effect function as an argument instead of the invoked return value. This means effect adapters can take full control of the effect and supply the effect function with arbitrary arguments, invoke the function multiple times, etc.

*Before*

[source, typescript]
----
@Injectable()
export class MyAdapter implements EffectAdapter<number> {
    create(value: Observable<number>, metadata: EffectMetadata) {
        return value.pipe(
            delay(500)
        )
    }
    next(value: number) {
        console.log(value)
    }
}
----

*After*

[source, typescript]
----
type EffectFn = (state: State<any>, customArg: string) => Observable<number>

@Injectable()
export class MyAdapter implements EffectAdapter<EffectFn> {
    constructor(private hostRef: HostRef) {}

    create(effectFn: EffectFn, metadata: EffectMetadata) {
        return effectFn(this.hostRef.state, "CUSTOM_ARG")
    }

    next(value: number) {
        console.log(value)
    }
}
----

== 9.0.0-rc.6

=== Features

- allow effects to run in modules
- allow adapters to transform effects
- allow effects to bind host emitters
- query hostRef outside of effects loop

=== Bug fixes

- don't obfuscate errors in local effect providers

=== Misc

- add `MapStateToProps` example

== 9.0.0-rc.5

=== Features

- effects no longer need to be provided with `effects()`
- rework `effects()` as an optional provider to configure defaults
- remove `HOST_EFFECTS` provider
- add `Effects` provider as a replacement for `effects()` and `HOST_EFFECTS`

=== Bug fixes

- fix typed metadata in effect adapters
- enforce return types when using effect adapters
- workaround for `InjectFlags.Self` (https://github.com/stupidawesome/ng-effects/issues/3)[#3])
- check if view destroyed before marking view dirty

=== Misc

- refactor effect explorer
- add tests for effect parameters

=== BREAKING CHANGES

`effects()` is now only used to optionally configure default options. To run effects, provide the `Effects` token along with any other effect providers. Host effects only need the `Effects` token to run.

*Before*

[source, typescript]
----
@Component({
    providers: [effects([MyEffects, ...etc]), MyAdapter] // or [HOST_EFFECTS]
})
export class AppComponent {
    @Effect(MyAdapter)
    hostEffect() {}

    constructor(connect: Connect) {
        connect(this)
    }
}
----

*After*

[source, typescript]
----
@Component({
    providers: [Effects, MyEffects, MyAdapter, ...etc] // or [Effects]
})
export class AppComponent {
    @Effect(MyAdapter)
    hostEffect() {}

    constructor(connect: Connect) {
        connect(this)
    }
}
----

Only effects provided at the same level as the component or directive will be executed. Effects are not inherited from parent injectors and must be provided in every component that uses it.

== 9.0.0-rc.4

=== Features

- add paramater decorators for `State`, `Context` and `Observe`
- refactor effect types to support additional use cases

[source, typescript]
----
class AppEffects {
    @Effect()
    incrementCount(@Context() context: Context<AppState>) {}
}
----

=== Misc

- remove `latestFrom` and roll it into `changes`
- use proxy in prod if supported

== 9.0.0-rc.3

- export missing tokens and tweak defaults

The default value of `markDirty` will now be `true` if the effect configures a `bind` or `assign` option. This is a better default in most cases, and can be configured by setting `@Effect("prop", { markDirty: false })`.

== 9.0.0-rc.2

=== Features

- expose experimental connect API

== 9.0.0-rc.1

=== Features

- add experimental global `connect` function
- add host observer as third argument to effect methods

=== Misc

- return cached metadata for already seen effect tokens
- create effects in effect runner instead of explorer
- create adapter in effect runner instead of explorer
- make `markDirty` calls synchronous unless in noop zone
- reduce usage of rxjs operators
- updated docs

=== BREAKING CHANGES

- remove `createEffect` factory
- rename `EffectHandler` to `EffectAdapter`
- `EffectAdapter` arguments are now just `value` and `metadata`. Options are now accessed through `metadata.options`
- update peer Angular dependencies to v9.0.0. Will backport to v8.0.0 when need arises

== 9.0.0-beta.10

=== Features

- add `HostEmitter` type for binding template/host events

=== Bug fixes

- fix unsubscribe errors

== 9.0.0-beta.9

=== Misc

- minor code refactor

`HostRef` property `instance` renamed to `context`

== 9.0.0-beta.8

=== Features

- better error reporting in dev mode when attempting to use uninitialised state in effects.

- add observable state to `HostRef`

`HostRef` now contains references to the observable state of the component or directive it is attached to. See docs for more information.

== 9.0.0-beta.7

=== Bug fixes
- fix more adapter effect types

== 9.0.0-beta.6

=== Bug fixes
- fix adapter effect types

== 9.0.0-beta.5

=== Bug fixes
- remove effect metadata cache

== 9.0.0-beta.4

=== Features
- adapters now receive effect metadata as a third argument

=== Bug fixes
- fix change detection bug

== 9.0.0-beta.3

=== Misc
- refactor internals for better code flow

== 9.0.0-beta.2

=== Features
- performance improvements
- add experimental zoneless event manager

=== Bug fixes
- fix max call stack errors

== 9.0.0-beta.1

=== Features

- defer state object creation until effect is called

State is proxied in dev mode to intercept and report uninitialised property access eg. `state.viewChildren`. This change allows Angular to bind properties before the state object is created by setting `whenRendered: true`.

== 9.0.0-beta.0

Initial release
