= Changelog

== 9.0.0-rc.5

=== Features

- rework `effects()` so that it no longer provides tokens it was passed to the injector
- remove `HOST_EFFECTS` provider
- add `Effects` provider as a replacement for `effects()` and `HOST_EFFECTS`

=== Bug fixes

- fix typed metadata in effect adapters
- enforce return types when using effect adapters

=== BREAKING CHANGES

`effects()` now only registers effect types with the `EFFECTS` provider. For effects to run, you must now provide the `Effects` token in addition to any effects to be run in your components and directives providers array.

*Before*

[source, typescript]
----
@Component({
    providers: [effects([MyEffects])]
})
export class AppComponent {
    @Effect()
    hostEffect() {}

    constructor(connect: Connect) {
        connect(this)
    }
}
----

*After*

Effects can now be registered in modules. If components or directives have host effects, add them here as well.

[source, typescript]
----
@NgModule({
    declarations: [AppComponent],
    providers: [effects([MyEffects, AppComponent])]
})
export class AppModule {}
----

Add effects that should be run to the component or directive providers array. Host effects only need to be registered as shown in the previous step. Other effects will only run when provided along with the `Effects` provider.

[source, typescript]
----
@Component({
    providers: [Effects, MyEffects]
})
export class AppComponent {
    @Effect()
    hostEffect() {}

    constructor(connect: Connect) {
        connect(this)
    }
}
----

This change simplifies the mental model and wiring of effects, which can now be treated like any other provider.

== 9.0.0-rc.4

=== Features

- add paramater decorators for `State`, `Context` and `Observe`
- refactor effect types to support additional use cases

[source, typescript]
----
class AppEffects {
    @Effect()
    incrementCount(@Context() context: Context<AppState>) {}
}
----

=== Misc

- remove `latestFrom` and roll it into `changes`
- use proxy in prod if supported

== 9.0.0-rc.3

- export missing tokens and tweak defaults

The default value of `markDirty` will now be `true` if the effect configures a `bind` or `assign` option. This is a better default in most cases, and can be configured by setting `@Effect("prop", { markDirty: false })`.

== 9.0.0-rc.2

=== Features

- expose experimental connect API

== 9.0.0-rc.1

=== Features

- add experimental global `connect` function
- add host observer as third argument to effect methods

=== Misc

- return cached metadata for already seen effect tokens
- create effects in effect runner instead of explorer
- create adapter in effect runner instead of explorer
- make `markDirty` calls synchronous unless in noop zone
- reduce usage of rxjs operators
- updated docs

=== BREAKING CHANGES

- remove `createEffect` factory
- rename `EffectHandler` to `EffectAdapter`
- `EffectAdapter` arguments are now just `value` and `metadata`. Options are now accessed through `metadata.options`
- update peer Angular dependencies to v9.0.0. Will backport to v8.0.0 when need arises

== 9.0.0-beta.10

=== Features

- add `HostEmitter` type for binding template/host events

=== Bug fixes

- fix unsubscribe errors

== 9.0.0-beta.9

=== Misc

- minor code refactor

`HostRef` property `instance` renamed to `context`

== 9.0.0-beta.8

=== Features

- better error reporting in dev mode when attempting to use uninitialised state in effects.

- add observable state to `HostRef`

`HostRef` now contains references to the observable state of the component or directive it is attached to. See docs for more information.

== 9.0.0-beta.7

=== Bug fixes
- fix more adapter effect types

== 9.0.0-beta.6

=== Bug fixes
- fix adapter effect types

== 9.0.0-beta.5

=== Bug fixes
- remove effect metadata cache

== 9.0.0-beta.4

=== Features
- adapters now receive effect metadata as a third argument

=== Bug fixes
- fix change detection bug

== 9.0.0-beta.3

=== Misc
- refactor internals for better code flow

== 9.0.0-beta.2

=== Features
- performance improvements
- add experimental zoneless event manager

=== Bug fixes
- fix max call stack errors

== 9.0.0-beta.1

=== Features

- defer state object creation until effect is called

State is proxied in dev mode to intercept and report uninitialised property access eg. `state.viewChildren`. This change allows Angular to bind properties before the state object is created by setting `whenRendered: true`.

== 9.0.0-beta.0

Initial release
